<a href="https://colab.research.google.com/github/AIML-ankit/MathForML/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

Shuffle tensorflow variable.. 

In [ ]:
unsuffled_variable = tf.constant([[2,3],
                                  [4,5],
                                  [6,7]])

In [ ]:
unsuffled_variable

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [6, 7]], dtype=int32)>

tf.random.shuffle()

In [ ]:
tf.random.shuffle(value=unsuffled_variable)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 7],
       [4, 5],
       [2, 3]], dtype=int32)>

In [ ]:
tf.random.shuffle(value=unsuffled_variable)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [2, 3],
       [6, 7]], dtype=int32)>

So in above two examples Shuffled value is different, lets try with seed value

In [ ]:
tf.random.shuffle(value=unsuffled_variable,seed =42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 7],
       [4, 5],
       [2, 3]], dtype=int32)>

In [ ]:
tf.random.shuffle(value=unsuffled_variable,seed =42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 7],
       [4, 5],
       [2, 3]], dtype=int32)>

So in above two example seed value is not working. 

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(value=unsuffled_variable)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7],
       [2, 3]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(value=unsuffled_variable)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7],
       [2, 3]], dtype=int32)>

Here if we giving tf.random.set.seed value than seed is working, why not if we giving seed value inside randon.shuffle? lets research this.

1 - If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
tf.random.set_seed(42)  #Global seed
tf.random.shuffle(value=unsuffled_variable,seed =31) #operation seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [6, 7],
       [4, 5]], dtype=int32)>

2- If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence. means no effect of operation seed.

In [ ]:
tf.random.shuffle(value=unsuffled_variable,seed =31)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 7],
       [4, 5],
       [2, 3]], dtype=int32)>

3- If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence.

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(value=unsuffled_variable)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7],
       [2, 3]], dtype=int32)>

# Creating tensor from numpy array.
Why we need this?

Calculation is much fast using numpy array as compare to tensorflow tensor

In [ ]:
numpy_A = np.arange(1,25,dtype=np.int16)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [ ]:
tf_numpy_A = tf.constant(numpy_A)
tf_numpy_A

<tf.Tensor: shape=(24,), dtype=int16, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)>

Here we can change the shape of numpy array by shpe option

In [ ]:
tf_numpy_B = tf.constant(numpy_A,shape=(2,3,4))
tf_numpy_B

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [ ]:
tf_numpy_C = tf.constant(numpy_A,shape=(4,3,2),dtype=tf.int32)
tf_numpy_C

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

Here we can also change the dtype

In [ ]:
tf_numpy_D = tf.constant(numpy_A,shape=(2,3,4),dtype=tf.int32)
tf_numpy_D

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>